
[
{
  "image_link": "https://api-ninjas.com/images/dogs/bearded_collie.jpg",
  "good_with_children": 5,
  "good_with_other_dogs": 5,
  "shedding": 3,
  "grooming": 4,
  "drooling": 1,
  "coat_length": 1,
  "good_with_strangers": 4,
  "playfulness": 4,
  "protectiveness": 3,
  "trainability": 3,
  "energy": 4,
  "barking": 5,
  "min_life_expectancy": 12,
  "max_life_expectancy": 14,
  "max_height_male": 22,
  "max_height_female": 22,
  "max_weight_male": 55,
  "max_weight_female": 55,
  "min_height_male": 21,
  "min_height_female": 21,
  "min_weight_male": 45,
  "min_weight_female": 45,
  "name": "Bearded Collie"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/border_collie.jpg",
  "good_with_children": 3,
  "good_with_other_dogs": 3,
  "shedding": 3,
  "grooming": 3,
  "drooling": 1,
  "coat_length": 1,
  "good_with_strangers": 4,
  "playfulness": 5,
  "protectiveness": 3,
  "trainability": 5,
  "energy": 5,
  "barking": 4,
  "min_life_expectancy": 12,
  "max_life_expectancy": 15,
  "max_height_male": 22,
  "max_height_female": 22,
  "max_weight_male": 55,
  "max_weight_female": 55,
  "min_height_male": 19,
  "min_height_female": 19,
  "min_weight_male": 30,
  "min_weight_female": 30,
  "name": "Border Collie"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/collie.jpg",
  "good_with_children": 5,
  "good_with_other_dogs": 3,
  "shedding": 3,
  "grooming": 3,
  "drooling": 2,
  "coat_length": 2,
  "good_with_strangers": 3,
  "playfulness": 4,
  "protectiveness": 3,
  "trainability": 4,
  "energy": 3,
  "barking": 5,
  "min_life_expectancy": 12,
  "max_life_expectancy": 14,
  "max_height_male": 26,
  "max_height_female": 26,
  "max_weight_male": 75,
  "max_weight_female": 65,
  "min_height_male": 24,
  "min_height_female": 24,
  "min_weight_male": 60,
  "min_weight_female": 50,
  "name": "Collie"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/golden_retriever.jpg",
  "good_with_children": 5,
  "good_with_other_dogs": 5,
  "shedding": 4,
  "grooming": 2,
  "drooling": 2,
  "coat_length": 1,
  "good_with_strangers": 5,
  "playfulness": 4,
  "protectiveness": 3,
  "trainability": 5,
  "energy": 3,
  "barking": 1,
  "min_life_expectancy": 10,
  "max_life_expectancy": 12,
  "max_height_male": 24,
  "max_height_female": 24,
  "max_weight_male": 75,
  "max_weight_female": 65,
  "min_height_male": 23,
  "min_height_female": 23,
  "min_weight_male": 65,
  "min_weight_female": 55,
  "name": "Golden Retriever"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/american_bulldog.jpg",
  "good_with_children": 3,
  "good_with_other_dogs": 3,
  "shedding": 2,
  "coat_length": 1,
  "trainability": 4,
  "barking": 1,
  "min_life_expectancy": 10,
  "max_life_expectancy": 12,
  "max_height_male": 28,
  "max_height_female": 24,
  "max_weight_male": 100,
  "max_weight_female": 80,
  "min_height_male": 20,
  "min_height_female": 20,
  "min_weight_male": 75,
  "min_weight_female": 60,
  "grooming": 0,
  "drooling": 0,
  "good_with_strangers": 0,
  "playfulness": 0,
  "protectiveness": 0,
  "energy": 0,
  "name": "American Bulldog"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/bulldog.jpg",
  "good_with_children": 3,
  "good_with_other_dogs": 3,
  "shedding": 3,
  "grooming": 3,
  "drooling": 3,
  "coat_length": 1,
  "good_with_strangers": 4,
  "playfulness": 4,
  "protectiveness": 3,
  "trainability": 4,
  "energy": 3,
  "barking": 2,
  "min_life_expectancy": 8,
  "max_life_expectancy": 10,
  "max_height_male": 15,
  "max_height_female": 15,
  "max_weight_male": 50,
  "max_weight_female": 40,
  "min_height_male": 14,
  "min_height_female": 14,
  "min_weight_male": 50,
  "min_weight_female": 40,
  "name": "Bulldog"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/french_bulldog.jpg",
  "good_with_children": 5,
  "good_with_other_dogs": 4,
  "shedding": 3,
  "grooming": 1,
  "drooling": 3,
  "coat_length": 1,
  "good_with_strangers": 5,
  "playfulness": 5,
  "protectiveness": 3,
  "trainability": 4,
  "energy": 3,
  "barking": 1,
  "min_life_expectancy": 10,
  "max_life_expectancy": 12,
  "max_height_male": 13,
  "max_height_female": 13,
  "max_weight_male": 28,
  "max_weight_female": 26,
  "min_height_male": 11,
  "min_height_female": 11,
  "min_weight_male": 20,
  "min_weight_female": 18,
  "name": "French Bulldog"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/american_hairless_terrier.jpg",
  "good_with_children": 5,
  "good_with_other_dogs": 3,
  "shedding": 1,
  "grooming": 1,
  "drooling": 1,
  "coat_length": 1,
  "good_with_strangers": 3,
  "playfulness": 3,
  "protectiveness": 3,
  "trainability": 5,
  "energy": 3,
  "barking": 3,
  "min_life_expectancy": 14,
  "max_life_expectancy": 16,
  "max_height_male": 16,
  "max_height_female": 16,
  "max_weight_male": 16,
  "max_weight_female": 16,
  "min_height_male": 12,
  "min_height_female": 12,
  "min_weight_male": 12,
  "min_weight_female": 12,
  "name": "American Hairless Terrier"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/american_staffordshire_terrier.jpg",
  "good_with_children": 3,
  "good_with_other_dogs": 3,
  "shedding": 2,
  "grooming": 1,
  "drooling": 1,
  "coat_length": 1,
  "good_with_strangers": 4,
  "playfulness": 3,
  "protectiveness": 5,
  "trainability": 3,
  "energy": 3,
  "barking": 3,
  "min_life_expectancy": 12,
  "max_life_expectancy": 16,
  "max_height_male": 19,
  "max_height_female": 19,
  "max_weight_male": 70,
  "max_weight_female": 55,
  "min_height_male": 18,
  "min_height_female": 18,
  "min_weight_male": 55,
  "min_weight_female": 40,
  "name": "American Staffordshire Terrier"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/boston_terrier.jpg",
  "good_with_children": 5,
  "good_with_other_dogs": 4,
  "shedding": 2,
  "grooming": 2,
  "drooling": 1,
  "coat_length": 1,
  "good_with_strangers": 5,
  "playfulness": 5,
  "protectiveness": 3,
  "trainability": 4,
  "energy": 4,
  "barking": 2,
  "min_life_expectancy": 11,
  "max_life_expectancy": 13,
  "max_height_male": 17,
  "max_height_female": 17,
  "max_weight_male": 25,
  "max_weight_female": 25,
  "min_height_male": 15,
  "min_height_female": 15,
  "min_weight_male": 12,
  "min_weight_female": 12,
  "name": "Boston Terrier"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/bull_terrier.jpg",
  "good_with_children": 3,
  "good_with_other_dogs": 1,
  "shedding": 3,
  "grooming": 2,
  "drooling": 1,
  "coat_length": 1,
  "good_with_strangers": 4,
  "playfulness": 4,
  "protectiveness": 3,
  "trainability": 3,
  "energy": 4,
  "barking": 3,
  "min_life_expectancy": 12,
  "max_life_expectancy": 13,
  "max_height_male": 22,
  "max_height_female": 22,
  "max_weight_male": 70,
  "max_weight_female": 70,
  "min_height_male": 21,
  "min_height_female": 21,
  "min_weight_male": 50,
  "min_weight_female": 50,
  "name": "Bull Terrier"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/irish_terrier.jpg",
  "good_with_children": 5,
  "good_with_other_dogs": 1,
  "shedding": 2,
  "grooming": 1,
  "drooling": 1,
  "coat_length": 1,
  "good_with_strangers": 3,
  "playfulness": 3,
  "protectiveness": 5,
  "trainability": 3,
  "energy": 3,
  "barking": 3,
  "min_life_expectancy": 13,
  "max_life_expectancy": 15,
  "max_height_male": 18,
  "max_height_female": 18,
  "max_weight_male": 27,
  "max_weight_female": 25,
  "min_height_male": 18,
  "min_height_female": 18,
  "min_weight_male": 27,
  "min_weight_female": 25,
  "name": "Irish Terrier"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/cavalier_king_charles_spaniel.jpg",
  "good_with_children": 5,
  "good_with_other_dogs": 5,
  "shedding": 2,
  "grooming": 2,
  "drooling": 2,
  "coat_length": 1,
  "good_with_strangers": 4,
  "playfulness": 3,
  "protectiveness": 3,
  "trainability": 4,
  "energy": 3,
  "barking": 3,
  "min_life_expectancy": 12,
  "max_life_expectancy": 15,
  "max_height_male": 13,
  "max_height_female": 13,
  "max_weight_male": 18,
  "max_weight_female": 18,
  "min_height_male": 12,
  "min_height_female": 12,
  "min_weight_male": 13,
  "min_weight_female": 13,
  "name": "Cavalier King Charles Spaniel"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/cocker_spaniel.jpg",
  "good_with_children": 5,
  "good_with_other_dogs": 5,
  "shedding": 3,
  "grooming": 4,
  "drooling": 2,
  "coat_length": 1,
  "good_with_strangers": 4,
  "playfulness": 3,
  "protectiveness": 3,
  "trainability": 4,
  "energy": 4,
  "barking": 3,
  "min_life_expectancy": 10,
  "max_life_expectancy": 14,
  "max_height_male": 15.5,
  "max_height_female": 15.5,
  "max_weight_male": 30,
  "max_weight_female": 25,
  "min_height_male": 14.5,
  "min_height_female": 14.5,
  "min_weight_male": 25,
  "min_weight_female": 20,
  "name": "Cocker Spaniel"
},
{
  "image_link": "https://api-ninjas.com/images/dogs/english_springer_spaniel.jpg",
  "good_with_children": 3,
  "good_with_other_dogs": 4,
  "shedding": 3,
  "grooming": 2,
  "drooling": 3,
  "coat_length": 1,
  "good_with_strangers": 4,
  "playfulness": 4,
  "protectiveness": 3,
  "trainability": 5,
  "energy": 4,
  "barking": 3,
  "min_life_expectancy": 12,
  "max_life_expectancy": 14,
  "max_height_male": 20,
  "max_height_female": 20,
  "max_weight_male": 50,
  "max_weight_female": 40,
  "min_height_male": 20,
  "min_height_female": 20,
  "min_weight_male": 50,
  "min_weight_female": 40,
  "name": "English Springer Spaniel"
}
]
